main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
]

notify_me/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("randomcharacterstring/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("projects/", include("projects.urls", namespace="projects")),
    path("users/", include("users.urls", namespace="users")),
    path("oauth/", include("oauth.urls", namespace="oauth")),
]

projects/urls.py
from django.urls import path

from projects import views

app_name = "projects"

urlpatterns = [
    path("", views.index, name="index"),
    path("add_project/", views.add_project, name="add_project"),
    path(
        "<int:project_id>/edit_project_balance/",
        views.edit_project_balance,
        name="edit_project_balance",
    ),
    path(
        "<int:project_id>/refresh_balance/",
        views.refresh_balance,
        name="refresh_balance",
    ),
    path("<int:project_id>/chats/", views.chats, name="chats"),
    path("<int:project_id>/chats/add_chat/", views.add_chat, name="add_chat"),
    path(
        "<int:project_id>/chats/send-test-notification/",
        views.send_test_notification,
        name="send_test_notification",
    ),
    path(
        "<int:project_id>/chats/<int:chat_id>/delete_chat/",
        views.delete_chat,
        name="delete_chat",
    ),
]

projects/models.py
from django.db import models

from users.models import User


class System(models.Model):
    name = models.CharField(max_length=255, verbose_name="Название")
    provider = models.CharField(max_length=255, verbose_name="Провайдер")

    class Meta:
        db_table = "system"
        verbose_name = "Система"
        verbose_name_plural = "Системы"

    def __str__(self):
        return self.name


class Project(models.Model):
    name = models.CharField(max_length=255, verbose_name="Название")
    login = models.EmailField(verbose_name="Логин")
    balance = models.DecimalField(
        max_digits=12, decimal_places=6, null=True, blank=True, verbose_name="Баланс"
    )
    threshold = models.BigIntegerField(verbose_name="Порог")
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="projects",
        verbose_name="Пользователь",
    )
    system = models.ForeignKey(
        System,
        on_delete=models.CASCADE,
        related_name="projects",
        verbose_name="Система",
    )
    balance_error = models.CharField(max_length=500, verbose_name="Ошибка баланса")

    class Meta:
        db_table = "project"
        verbose_name = "Проект"
        verbose_name_plural = "Проекты"

    def __str__(self):
        return self.name


class Chat(models.Model):
    chat_id = models.BigIntegerField(verbose_name="Идентификатор телеграм чата")
    comment = models.CharField(max_length=255, verbose_name="Комментарий")
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name="chats",
        verbose_name="Проект",
    )
    test_notification_error = models.CharField(
        max_length=500, verbose_name="Ошибка отправки уведомления"
    )

    class Meta:
        db_table = "chat"
        verbose_name = "Чат"
        verbose_name_plural = "Чаты"

    def __str__(self):
        return f"[{self.chat_id}]({self.comment}): '{self.project.name}'"

projects/forms.py
from django.forms import ModelForm, ModelChoiceField

from projects.models import Project, System, Chat


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ["name", "system", "login", "threshold"]

    system = ModelChoiceField(queryset=System.objects.all())


class ChatForm(ModelForm):
    class Meta:
        model = Chat
        fields = ["chat_id", "comment"]

projects/views.py
from decimal import Decimal
from django.urls import reverse
import requests

from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from check_balance import get_current_balance
from oauth.utils import get_access_token
from projects.models import Project, Chat
from projects.forms import ProjectForm, ChatForm

from notify_me import settings


@login_required
def index(request):
    projects = Project.objects.filter(user=request.user)

    context = {"title": "Проекты", "projects": projects}

    return render(request, "projects/index.html", context)


@login_required
def add_project(request):
    if request.method == "POST":
        form = ProjectForm(data=request.POST)
        if form.is_valid():
            system = form.cleaned_data["system"]
            provider = system.provider

            project = form.save(commit=False)
            project.user = request.user
            project.save()

            request.session["project_id"] = project.id
            request.session["next_url"] = reverse("projects:edit_project_balance", kwargs={"project_id": project.id})

            return redirect("oauth:oauth_login", provider=provider)
    else:
        form = ProjectForm()

    context = {"title": "Добавить проект", "form": form}

    return render(request, "projects/add_project.html", context)


@login_required
def edit_project_balance(request, project_id):
    project = Project.objects.get(id=project_id, user=request.user)

    access_token = get_access_token(request.user, project)

    if not access_token:
        project.balance_error = "Нет токена доступа для данного проекта"
        project.save()

        return redirect("projects:index")

    response_data = get_current_balance(access_token)

    response_data = response_data.json()

    if "data" in response_data:
        if response_data["data"]["Accounts"]:
            amount = response_data["data"]["Accounts"][0].get("Amount")

            project.balance = Decimal(amount)
            project.balance_error = ""
            project.save()

            return redirect("projects:chats", project_id=project_id)
        else:
            error = response_data["data"]["ActionsResult"][0]["Errors"][0]

            # Ошибка данных
            error_msg = f"{error.get('FaultCode')} {error.get('FaultString')} {error.get('FaultDetail')}"
    else:
        # Структурная ошибка
        error_msg = f"{response_data.get('error_code')} {response_data.get('error_str')} {response_data.get('error_detail')}"

    project.balance_error = error_msg
    project.save()

    return redirect("projects:index")


@login_required
def refresh_balance(request, project_id):
    project = Project.objects.get(id=project_id, user=request.user)

    access_token = get_access_token(request.user, project)

    if not access_token:
        project.balance_error = "Нет токена доступа для данного проекта"
        project.save()

        return redirect("projects:index")

    response_data = get_current_balance(access_token)

    response_data = response_data.json()

    if "data" in response_data:
        if response_data["data"]["Accounts"]:
            amount = response_data["data"]["Accounts"][0].get("Amount")

            project.balance = Decimal(amount)
            project.balance_error = ""
        else:
            error = response_data["data"]["ActionsResult"][0]["Errors"][0]

            # Ошибка данных
            error_msg = f"{error.get('FaultCode')} {error.get('FaultString')} {error.get('FaultDetail')}"

            project.balance_error = error_msg
    else:
        # Структурная ошибка
        error_msg = f"{response_data.get('error_code')} {response_data.get('error_str')} {response_data.get('error_detail')}"

        project.balance_error = error_msg

    project.save()

    return redirect("projects:index")


@login_required
def chats(request, project_id):
    project = get_object_or_404(Project, id=project_id, user_id=request.user.id)

    chats = project.chats.all()

    test_notification_error_key = next(
        (key for key in request.session.keys() if "test_notification_error_" in key),
        None,
    )

    if test_notification_error_key:
        test_chat_id = test_notification_error_key.replace(
            "test_notification_error_", ""
        )
        test_notification_error = request.session.pop(test_notification_error_key)
    else:
        test_notification_error = ""
        test_chat_id = ""

    context = {
        "title": "Список чатов проекта",
        "project_id": project_id,
        "chats": chats,
        "test_notification_error": test_notification_error,
        "test_chat_id": test_chat_id,
    }

    return render(request, "projects/chats.html", context)


@login_required
def add_chat(request, project_id):
    project = get_object_or_404(Project, id=project_id, user=request.user)

    form = ChatForm(data=request.POST)
    if form.is_valid():
        chat = form.save(commit=False)
        chat.project = project
        chat.save()

        return redirect("projects:chats", project_id=project_id)
    else:
        chats = Chat.objects.filter(project_id=project_id)

        context = {
            "title": "Список чатов проекта",
            "project_id": project_id,
            "form": form,
            "chats": chats,
        }

        return render(request, "projects/chats.html", context)


@login_required
def send_test_notification(request, project_id):
    chat_id = request.GET.get("chat_id")
    is_new = request.GET.get("is_new", None)

    project = Project.objects.get(id=project_id, user=request.user)

    message = "Тестовое уведомление"

    try:
        response_data = requests.get(
            f"https://api.telegram.org/bot{settings.TELEGRAM_TOKEN}/sendMessage?chat_id={chat_id}&text={message}"
        )

        if not response_data.status_code == 200:
            response_data = response_data.json()

            if is_new:
                request.session[f"test_notification_error_{chat_id}"] = f"{response_data['error_code']} {response_data['description']}"
            else:
                try:
                    chat = Chat.objects.get(chat_id=chat_id, project=project)
                    chat.test_notification_error = (
                        f"{response_data['error_code']} {response_data['description']}"
                    )
                    chat.save()
                except Chat.DoesNotExist as e:
                    request.session[f"test_notification_error_{chat_id}"] = f"Ошибка: {str(e)}"

        return redirect("projects:chats", project_id=project_id)
    except Exception as e:
        request.session[f"test_notification_error_{chat_id}"] = f"Ошибка: {str(e)}"

        return redirect("projects:chats", project_id=project_id)


@login_required
def delete_chat(request, project_id, chat_id):
    project = Project.objects.get(id=project_id, user=request.user)

    if project:
        chat = Chat.objects.get(id=chat_id, project=project)
        chat.delete()

        return redirect("projects:chats", project_id=project_id)
    else:
        return redirect("projects:index")

projects/templates/projects/add_project.html
{% extends "base.html" %}

{% block content %}
    <main class="row g-0 justify-content-center my-auto">
        <div class="px-3 py-3 px-sm-0 col-sm-8 col-lg-6 col-xl-4">
            <div class="p-3 border border-3 border-success rounded-4 bg-success-subtle">
                <form class="row g-0 needs-validation" action="{% url "projects:add_project" %}" method="post" novalidate>
                    {% csrf_token %}
                    <div class="mb-2">
                        <label for="id_name" class="form-label">Название проекта</label>
                        <input type="text" id="id_name" class="form-control {% if form.name.errors %}is-invalid{% endif %}" placeholder="Название проекта" name="name" value="{{ form.name.value|default_if_none:'' }}" required>
                        {% if form.name.errors %}
                            <div class="invalid-feedback">
                                {{ form.name.errors|striptags }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="mb-2">
                        <label for="system" class="form-label">Система</label>
                        <select id="system" class="form-select {% if form.system.errors %}is-invalid{% endif %}" name="system" required>
                            <option value="" selected disabled hidden>Выберите систему</option>
                            {% for system in form.fields.system.queryset %}
                                <option value="{{ system.id }}" {% if system.id == form.system.value %}selected{% endif %}>{{ system.name }}</option>
                            {% endfor %}
                        </select>
                        {% if form.system.errors %}
                            <div class="invalid-feedback">
                                {{ form.system.errors|striptags }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="mb-2">
                        <label for="id_login" class="form-label">Логин</label>
                        <input type="email" id="id_login" class="form-control {% if form.login.errors %}is-invalid{% endif %}" placeholder="Емэйл в системе" name="login" value="{{ form.login.value|default_if_none:'' }}" required>
                        {% if form.login.errors %}
                            <div class="invalid-feedback">
                                {{ form.login.errors|striptags }}
                            </div>
                        {% endif %}            
                    </div>
                    <div class="mb-5">
                        <label for="threshold" class="form-label">Порог</label>
                        <input type="number" id="threshold" class="form-control {% if form.threshold.errors %}is-invalid{% endif %}" placeholder="Пороговое значение" name="threshold" value="{{ form.threshold.value|default_if_none:'' }}" required>
                        {% if form.threshold.errors %}
                            <div class="invalid-feedback">
                                {{ form.threshold.errors|striptags }}
                            </div>
                        {% endif %}
                    </div>
                    <div class="text-center text-sm-start">
                        <button type="submit" class="btn btn-primary px-5 fw-bold">Далее</button>
                    </div>
                </form>
            </div>
        </div>
    </main>
{% endblock %}

projects/templates/projects/chats.html
{% extends "base.html" %}

{% block content %}
    <main class="row g-0 gap-2 justify-content-center my-5 px-1">
        <div class="text-center mb-4">Перед добавлением чата добавьте себе этого бота: <span class="text-primary fw-bold">t.me/ntf_m_bot</span></div>
        <div class="col-12 mb-4">
            <form class="row g-0 justify-content-center justify-content-lg-end needs-validation" action="{% url 'projects:add_chat' project_id=project_id %}" method="post" novalidate>
                {% csrf_token %}
                <div class="col-6 col-sm-auto ms-lg-auto">
                    <input id="chat_id" type="number" class="form-control rounded-end-0 {% if form.chat_id.errors %}is-invalid{% endif %}" placeholder="ID" name="chat_id" value="{% if form %}{{ form.chat_id.value|default_if_none:'' }}{% else %}{{ test_chat_id|default_if_none:'' }}{% endif %}" required>
                    {% if form.chat_id.errors %}
                        <div id="invalid_chat_id_feedback" class="invalid-feedback">
                            {{ form.chat_id.errors|striptags }}
                        </div>
                    {% endif %}
                    <span class="text-danger fw-bold">{{ test_notification_error }}</span>
                </div>
                <div class="col-6 col-sm-auto me-sm-2 mb-2 mb-md-0">
                    <input type="text" class="form-control rounded-start-0 {% if form.comment.errors %}is-invalid{% endif %}" placeholder="Комментарий" name="comment" value="{{ form.comment.value|default_if_none:'' }}" required>
                    {% if form.comment.errors %}
                        <div class="invalid-feedback">
                            {{ form.comment.errors|striptags }}
                        </div>
                    {% endif %}
                </div>
                <div class="col-sm-auto btn-group align-self-start" role="group">
                    <a id="test-btn" href="{% url 'projects:send_test_notification' project_id=project_id %}?is_new=1" class="btn btn-outline-primary fw-bold">Тест</a>
                    <button type="submit" class="btn btn-primary fw-bold">Добавить</button>
                </div>
            </form>
        </div>
        <div class="col-12 text-center lh-sm">
            <div class="table-responsive">
                <table class="table table-bordered border-success table-striped align-middle w-100">
                    <tr>
                        <th class="bg-success text-white">№</th>
                        <th class="bg-success text-white">ID</th>
                        <th class="bg-success text-white w-50">Комментарий</th>
                        <th class="bg-success text-white">Действия</th>
                    </tr>
                    {% if chats|length != 0 %}
                        {% for chat in chats %}
                            <tr class="{% if forloop.counter|divisibleby:2 == True %}table-success border border-success{% endif %}">
                                <td class="">{{ forloop.counter }}</td>
                                <td>
                                    <a href="tg://resolve?domain={{ chat.chat_id }}"
                                        class="link-primary link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover">{{ chat.chat_id }}</a>
                                </td>
                                <td class="w-50">
                                    <div class="d-flex flex-column justify-content-center align-items-center">
                                        <div class="mb-1">{{ chat.comment }}</div>
                                        <span class="text-danger fw-bold">{{ chat.test_notification_error }}</span>
                                    </div>
                                </td>
                                <td>
                                    <div class="row g-0 align-items-center justify-content-center">
                                        <div class="col-auto me-lg-2 mb-2 mb-lg-0">
                                            <a href="{% url 'projects:send_test_notification' project_id=project_id %}?chat_id={{ chat.chat_id }}"
                                                class="link-dark link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover">Отправить
                                                тестовое</a>
                                        </div>
                                        <div class="col-auto me-2 d-none d-lg-block">|</div>
                                        <div class="col-auto"><a href="{% url 'projects:delete_chat' project_id=project_id chat_id=chat.id %}"
                                                class="link-dark link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover">Удалить</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="4">
                                <div class="p-3">
                                    Вы пока не добавили ниодного чата.
                                </div>
                            </td>
                        </tr>
                    {% endif %}
                </table>
            </div>
        </div>
    </main>

    <script>
        document.getElementById('test-btn').addEventListener('click', function(event) {
            event.preventDefault();

            const chatIdInput = document.getElementById('chat_id');

            if(chatIdInput.value) {
                const currentHref = this.href;

                this.href = currentHref + "&chat_id=" + encodeURIComponent(chatIdInput.value);

                window.location.href = this.href;
            } else {
                chatIdInput.classList.add('is-invalid');

                let feedbackElement = document.getElementById('invalid_chat_id_feedback');
                if (!feedbackElement) {
                    feedbackElement = document.createElement('div');
                    feedbackElement.id = 'invalid_chat_id_feedback';
                    feedbackElement.classList.add('invalid-feedback');
                    chatIdInput.parentNode.appendChild(feedbackElement);
                }

                feedbackElement.textContent = 'Обязательное поле.';
                feedbackElement.style.display = 'block';
            }
        });
    </script>
{% endblock %}

projects/templates/projects/index.html
{% extends "base.html" %}

{% block content %}
    <main class="row g-0 gap-2 justify-content-center my-5 px-1">
        <div class="col-auto ms-md-auto">
            <a href="{% url "projects:add_project" %}" class="d-none d-md-inline-block btn btn-primary" data-bs-toggle="tooltip"
                data-bs-placement="left" data-bs-title="Добавить проект"><span class="icon-plus"></span></a>
            <a href="{% url "projects:add_project" %}" class="d-inline-block d-md-none btn btn-primary">Добавить проект</a>
        </div>
        <div class="w-100"></div>
        <div class="col-12 text-center lh-sm">
            <div class="table-responsive">
                <table class="table table-bordered border-success table-striped align-middle w-100">
                    <tr>
                        <th class="bg-success text-white">№</th>
                        <th class="bg-success text-white w-25">Название</th>
                        <th class="bg-success text-white">Система</th>
                        <th class="bg-success text-white">Логин</th>
                        <th class="bg-success text-white">Баланс</th>
                        <th class="bg-success text-white">Порог</th>
                        <th class="bg-success text-white">Действия</th>
                    </tr>
                    {% if projects|length != 0 %}
                        {% for project in projects %}
                            <tr class="{% if forloop.counter|divisibleby:2 == True %}table-success border border-success{% endif %}">
                                <td class="">{{ forloop.counter }}</td>
                                <td class="w-25">
                                    <div class="d-flex flex-column justify-content-center align-items-center">
                                        <div class="mb-1">{{ project.name }}</div>
                                        <span class="text-danger fw-bold">{{ project.balance_error }}</span>
                                    </div>
                                </td>
                                <td>{{ project.system.name }}</td>
                                <td>{{ project.login }}</td>
                                <td>
                                    <div class="row g-0 align-items-center justify-content-around">
                                        <span class="col-xl-6 text-xl-center mb-2 mb-xl-0
                                            {% if project.balance is not None and project.balance < project.threshold %}text-danger fs-5{% endif %}">
                                            {% if project.balance is not None %}
                                                {{ project.balance|floatformat:0 }}
                                            {% else %}
                                                &mdash;
                                            {% endif %}
                                        </span>
                                        <div class="col-xl-6 text-xl-center">
                                            <a href="{% url "projects:refresh_balance" project_id=project.id %}" class="btn btn-primary rounded-circle p-auto" data-bs-toggle="tooltip"
                                                data-bs-placement="right" data-bs-title="Обновить баланс">
                                                <span class="icon-refresh"></span>
                                            </a>
                                        </div>
                                    </div>
                                </td>
                                <td>{{ project.threshold }}</td>
                                <td>
                                    <div class="row g-0 align-items-center justify-content-center">
                                        <div class="col-auto me-lg-2 mb-2 mb-lg-0">
                                            <a href="#"
                                                class="link-dark link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover">Изменить</a>
                                        </div>
                                        <div class="col-auto me-lg-2 mb-2 mb-lg-0"><a href="{% url "projects:chats" project_id=project.id %}"
                                                class="link-dark link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover">Чаты</a>
                                        </div>
                                        <div class="col-auto"><a href="#"
                                                class="link-dark link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover">В
                                                архив</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td colspan="7">
                                <div class="p-3">
                                    Вы пока не добавили ниодного проекта.
                                </div>
                            </td>
                        </tr>
                    {% endif %}
                </table>
            </div>
        </div>
        <div class="col-auto ms-md-auto">
            <button class="d-none d-md-inline-block btn btn-primary" data-bs-toggle="tooltip"
                data-bs-placement="left" data-bs-title="Проекты в архиве"><span
                    class="icon-archive"></span></button>
            <button class="d-inline-block d-md-none btn btn-primary">Проекты в архиве</button>
        </div>
    </main>
{% endblock %}