main/urls.py
from django.urls import path

from main import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
]

notify_me/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("randomcharacterstring/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("projects/", include("projects.urls", namespace="projects")),
    path("users/", include("users.urls", namespace="users")),
    path("oauth/", include("oauth.urls", namespace="oauth")),
]

users/urls.py
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("signin/", views.signin, name="signin"),
    path("signout/", views.signout, name="signout"),
]

main/views.py
from django.shortcuts import redirect


def index(request):
    return redirect("projects:index")

main/templates/main/base.html
{% load static %}

<!doctype html>
<html lang="ru">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "icomoon/style.css" %}">
    <link rel="stylesheet" href="{% static "style.css" %}">
</head>

<body>
    <div class="container g-0">
        <div class="d-flex flex-column min-vh-100">
            <nav class="navbar navbar-expand-sm bg-body-tertiary">
                <div class="container-fluid">
                    <a class="navbar-brand fw-medium text-uppercase" href="{% url "main:index" %}">Главная</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-lg-0 text-center fw-medium">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url "main:about" %}">О приложении</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url "projects:index" %}">Проекты</a>
                            </li>
                        </ul>
                        <div id="signin">
                            <div class="d-none d-sm-flex">
                                <a class="icon-link link-secondary link-underline-secondary link-underline-opacity-0"
                                    href="{% url "users:signin" %}" data-bs-toggle="tooltip" data-bs-placement="left"
                                    data-bs-title="Вход">
                                    <div class="icon-enter fs-3"></div>
                                </a>
                            </div>
                            <div class="d-block d-sm-none">
                                <div class="text-center py-2">
                                    <a href="{% url "users:signin" %}"
                                        class="link-secondary link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover fw-medium">
                                        Вход
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div id="signout" class="d-none">
                            <div class="d-none d-sm-flex">
                                <a class="icon-link link-secondary link-underline-secondary link-underline-opacity-0"
                                    href="./login.html" data-bs-toggle="tooltip" data-bs-placement="left"
                                    data-bs-title="Выход">
                                    <div class="icon-exit fs-3"></div>
                                </a>
                            </div>
                            <div class="d-block d-sm-none">
                                <div class="text-center py-2">
                                    <a href="./login.html"
                                        class="link-secondary link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover fw-medium">
                                        Выход
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
    
            {% block content %}{% endblock %}
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <script src="{% static "script.js" %}"></script>
</body>

</html>